[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.30", features = ["derive"] }
time = "0.3.37"
typed-builder = "0.20.0"
log = "0.4.26"
env_logger = "0.11.6"
