name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build raven
      run: cargo build --locked --verbose --release -p raven

    - name: Build raven-common
      run: cargo build --locked --verbose --release -p raven-common

    - name: Build raven-common
      run: cargo build --locked --verbose --release -p raven-database

    - name: Build main
      run: cargo build --all --locked --verbose

    - name: Run tests
      run: cargo test --all --locked --verbose

